import { defineConfig } from 'vite-plus'

export default defineConfig({
  staged: {
    '**/*.{js,ts,jsx,tsx,mjs,cjs,json,jsonc,md,mdx,html,vue,css,less,scss}': 'cspell',
    '**/*.{css,scss,less,vue}': 'stylelint --fix',
    '**/*.{js,ts,jsx,tsx,json,jsonc,md,mdx,html}': 'vp fmt',
    '**/*.{js,ts,jsx,tsx,mjs,cjs}': 'vp lint --fix'
  },
  lint: {
    ignorePatterns: [
      '**/node_modules/**',
      '**/dist/**',
      '**/dist-ssr/**',
      'scripts/**',
      '**/.turbo/**',
      '**/routeTree.gen.ts',
      '**/.eslintrc-auto-import.js',
      '**/auto-imports.d.ts',
      '**/wailsjs/**'
    ],
    overrides: [
      {
        files: ['**/*.{ts,tsx,vue}'],
        rules: {
          '@typescript-eslint/no-explicit-any': 'warn',
          '@typescript-eslint/no-unsafe-declaration-merging': 'warn',

          'no-unused-vars': 'warn',
          'no-redeclare': 'error',
          'constructor-super': 'off',
          'getter-return': 'off',
          'no-class-assign': 'off',
          'no-const-assign': 'off',
          'no-dupe-class-members': 'off',
          'no-dupe-keys': 'off',
          'no-func-assign': 'off',
          'no-import-assign': 'off',
          'no-new-native-nonconstructor': 'off',
          'no-obj-calls': 'off',
          'no-setter-return': 'off',
          'no-this-before-super': 'off',
          'no-undef': 'off',
          'no-unreachable': 'off',
          'no-unsafe-negation': 'off',
          'no-var': 'error',
          'no-with': 'off',
          'prefer-const': 'error',
          'prefer-rest-params': 'error',
          'prefer-spread': 'error',
          '@typescript-eslint/ban-ts-comment': 'error',
          'no-array-constructor': 'error',
          '@typescript-eslint/no-duplicate-enum-values': 'error',
          '@typescript-eslint/no-empty-object-type': 'error',
          '@typescript-eslint/no-extra-non-null-assertion': 'error',
          '@typescript-eslint/no-misused-new': 'error',
          '@typescript-eslint/no-namespace': 'error',
          '@typescript-eslint/no-non-null-asserted-optional-chain': 'error',
          '@typescript-eslint/no-require-imports': 'error',
          '@typescript-eslint/no-this-alias': 'error',
          '@typescript-eslint/no-unnecessary-type-constraint': 'error',
          '@typescript-eslint/no-unsafe-function-type': 'error',
          'no-unused-expressions': 'error',
          '@typescript-eslint/no-wrapper-object-types': 'error',
          '@typescript-eslint/prefer-as-const': 'error',
          '@typescript-eslint/prefer-namespace-keyword': 'error'
          // '@typescript-eslint/triple-slash-reference': 'error'
        }
      },
      {
        files: ['**/*.{js,mjs,cjs,jsx,ts,tsx,vue}'],
        rules: {
          'constructor-super': 'error',
          'for-direction': 'error',
          'getter-return': 'error',
          'no-async-promise-executor': 'error',
          'no-case-declarations': 'error',
          'no-class-assign': 'error',
          'no-compare-neg-zero': 'error',
          'no-cond-assign': 'error',
          'no-const-assign': 'error',
          'no-console': 'off',
          'no-constant-binary-expression': 'error',
          'no-constant-condition': 'error',
          'no-control-regex': 'error',
          'no-debugger': 'error',
          'no-delete-var': 'error',
          'no-dupe-class-members': 'error',
          'no-dupe-else-if': 'error',
          'no-dupe-keys': 'error',
          'no-duplicate-case': 'error',
          'no-empty': 'error',
          'no-empty-character-class': 'error',
          'no-empty-pattern': 'error',
          'no-empty-static-block': 'error',
          'no-ex-assign': 'error',
          'no-extra-boolean-cast': 'error',
          'no-fallthrough': 'error',
          'no-func-assign': 'error',
          'no-global-assign': 'error',
          'no-import-assign': 'error',
          'no-invalid-regexp': 'error',
          'no-irregular-whitespace': 'error',
          'no-loss-of-precision': 'error',
          'no-misleading-character-class': 'error',
          'no-new-native-nonconstructor': 'error',
          'no-nonoctal-decimal-escape': 'error',
          'no-obj-calls': 'error',
          'no-prototype-builtins': 'error',
          'no-redeclare': 'off',
          'no-regex-spaces': 'error',
          'no-self-assign': 'error',
          'no-setter-return': 'error',
          'no-shadow-restricted-names': 'error',
          'no-sparse-arrays': 'error',
          'no-this-before-super': 'error',
          'no-undef': 'off',
          'no-unexpected-multiline': 'error',
          'no-unreachable': 'error',
          'no-unsafe-finally': 'error',
          'no-unsafe-negation': 'error',
          'no-unsafe-optional-chaining': 'error',
          'no-unused-labels': 'error',
          'no-unused-private-class-members': 'error',
          'no-unused-vars': 'off',
          'no-useless-backreference': 'error',
          'no-useless-catch': 'error',
          'no-useless-escape': 'error',
          'no-with': 'error',
          'require-yield': 'error',
          'use-isnan': 'error',
          'valid-typeof': 'error',
          'vue/no-arrow-functions-in-watch': 'error',
          'vue/no-deprecated-destroyed-lifecycle': 'error',
          'vue/no-export-in-script-setup': 'error',
          'vue/no-lifecycle-after-await': 'error',
          'vue/prefer-import-from-vue': 'error',
          'vue/valid-define-emits': 'error',
          'vue/valid-define-props': 'error',
          'vue/no-multiple-slot-args': 'warn',
          'vue/no-required-prop-with-default': 'warn'
        },
        plugins: ['vue'],
        env: {
          browser: true,
          es2026: true,
          node: true
        },
        globals: {
          Component: 'writable',
          ComponentPublicInstance: 'writable',
          ComputedRef: 'writable',
          DirectiveBinding: 'writable',
          EffectScope: 'writable',
          ExtractDefaultPropTypes: 'writable',
          ExtractPropTypes: 'writable',
          ExtractPublicPropTypes: 'writable',
          InjectionKey: 'writable',
          MaybeRef: 'writable',
          MaybeRefOrGetter: 'writable',
          PropType: 'writable',
          Ref: 'writable',
          ShallowRef: 'writable',
          Slot: 'writable',
          Slots: 'writable',
          VNode: 'writable',
          WritableComputedRef: 'writable',
          computed: 'writable',
          createApp: 'writable',
          customRef: 'writable',
          defineAsyncComponent: 'writable',
          defineComponent: 'writable',
          effectScope: 'writable',
          getCurrentInstance: 'writable',
          getCurrentScope: 'writable',
          getCurrentWatcher: 'writable',
          inject: 'writable',
          isProxy: 'writable',
          isReactive: 'writable',
          isReadonly: 'writable',
          isRef: 'writable',
          isShallow: 'writable',
          markRaw: 'writable',
          nextTick: 'writable',
          onActivated: 'writable',
          onBeforeMount: 'writable',
          onBeforeUnmount: 'writable',
          onBeforeUpdate: 'writable',
          onDeactivated: 'writable',
          onErrorCaptured: 'writable',
          onMounted: 'writable',
          onRenderTracked: 'writable',
          onRenderTriggered: 'writable',
          onScopeDispose: 'writable',
          onServerPrefetch: 'writable',
          onUnmounted: 'writable',
          onUpdated: 'writable',
          onWatcherCleanup: 'writable',
          provide: 'writable',
          reactive: 'writable',
          readonly: 'writable',
          ref: 'writable',
          resolveComponent: 'writable',
          shallowReactive: 'writable',
          shallowReadonly: 'writable',
          shallowRef: 'writable',
          toRaw: 'writable',
          toRef: 'writable',
          toRefs: 'writable',
          toValue: 'writable',
          triggerRef: 'writable',
          unref: 'writable',
          useAttrs: 'writable',
          useCssModule: 'writable',
          useCssVars: 'writable',
          useId: 'writable',
          useModel: 'writable',
          useSlots: 'writable',
          useTemplateRef: 'writable',
          watch: 'writable',
          watchEffect: 'writable',
          watchPostEffect: 'writable',
          watchSyncEffect: 'writable'
        }
      },
      {
        files: ['**/*.{js,jsx,ts,tsx}'],
        plugins: ['react'],
        rules: {
          'react/display-name': 'off',
          'react/jsx-key': 'error',
          'react/jsx-no-comment-textnodes': 'error',
          'react/jsx-no-duplicate-props': 'error',
          'react/jsx-no-target-blank': 'error',
          'react/jsx-no-undef': 'error',
          'react/no-children-prop': 'error',
          'react/no-danger-with-children': 'error',
          'react/no-direct-mutation-state': 'error',
          'react/no-find-dom-node': 'error',
          'react/no-is-mounted': 'error',
          'react/no-render-return-value': 'error',
          'react/no-string-refs': 'error',
          'react/no-unescaped-entities': 'error',
          'react/no-unknown-property': 'error',
          'react/no-unsafe': 'off',
          'react/react-in-jsx-scope': 'off',
          'react/require-render-return': 'error',
          'react/rules-of-hooks': 'error',
          'react/exhaustive-deps': 'warn',
          'react/only-export-components': 'off'
        }
      },
      {
        files: ['**/*.{test,spec}.{js,ts,jsx,tsx}'],
        rules: {
          'vitest/expect-expect': 'error',
          'vitest/no-conditional-expect': 'error',
          'vitest/no-disabled-tests': 'warn',
          'vitest/no-focused-tests': 'error',
          'vitest/no-commented-out-tests': 'error',
          'vitest/no-identical-title': 'error',
          'vitest/no-import-node-test': 'error',
          'vitest/no-interpolation-in-snapshots': 'error',
          'vitest/no-mocks-import': 'error',
          'vitest/no-standalone-expect': 'error',
          'vitest/no-unneeded-async-expect-function': 'error',
          'vitest/require-local-test-context-for-concurrent-snapshots': 'error',
          'vitest/valid-describe-callback': 'error',
          'vitest/valid-expect': 'error'
        },
        plugins: ['vitest'],
        env: {
          browser: true,
          node: true,
          vitest: true
        }
      },
      {
        files: ['**/*.{test,spec}.{js,ts,jsx,tsx}'],
        rules: {
          'no-console': 'off',
          '@typescript-eslint/no-explicit-any': 'off',
          '@typescript-eslint/unbound-method': 'off'
        }
      },
      {
        files: ['packages/web-ui/src/components/**/*.ts'],
        rules: {
          '@typescript-eslint/unbound-method': 'off'
        }
      }
    ],
    options: {
      typeAware: true,
      typeCheck: true
    }
  },
  fmt: {
    printWidth: 120,
    tabWidth: 2,
    useTabs: false,
    singleQuote: true,
    semi: false,
    trailingComma: 'none',
    bracketSpacing: true,
    arrowParens: 'avoid',
    sortPackageJson: false,
    ignorePatterns: [
      '/dist/*',
      '/dist-ssr/*',
      '/dev-dist/*',
      '.local',
      '.output.js',
      '/node_modules/**',
      '**/*.svg',
      '**/*.sh',
      '/public/*',
      '**/routeTree.gen.ts',
      '/wailsjs/**'
    ],
    experimentalSortImports: {
      enabled: true,
      groups: ['builtin', 'external', 'internal', 'parent', 'sibling', 'index']
    }
  },
  test: {
    environment: 'jsdom'
  }
})
