// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * IndexService 负责全量扫描：校验条目、补齐监听根内新文件、尝试唯一候选自动修复。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * GetStats 返回库统计信息。
 */
export function GetStats(): $CancellablePromise<$models.Stats> {
    return $Call.ByID(1135256013).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * Rescan 执行全量扫描并返回摘要。
 */
export function Rescan(): $CancellablePromise<$models.RescanResult> {
    return $Call.ByID(868791006).then(($result: any) => {
        return $$createType1($result);
    });
}

// Private type creation functions
const $$createType0 = $models.Stats.createFrom;
const $$createType1 = $models.RescanResult.createFrom;
