// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ItemService 负责条目的查询与入库（可寻址资源：file / url）。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * AddFiles 添加一个或多个文件（保持原位，仅登记）。
 */
export function AddFiles(paths: string[], tagPaths: string[]): $CancellablePromise<$models.AddResult> {
    return $Call.ByID(1933168585, paths, tagPaths).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * AddFolder 递归索引目录内每个文件为扁平条目，并登记为监听根。
 */
export function AddFolder(path: string, tagPaths: string[]): $CancellablePromise<$models.AddResult> {
    return $Call.ByID(267558134, path, tagPaths).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * AddUrl 添加远程资源链接。
 */
export function AddUrl(rawURL: string, tagPaths: string[]): $CancellablePromise<$models.Item> {
    return $Call.ByID(3955703895, rawURL, tagPaths).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * GetItem 返回单个条目。
 */
export function GetItem(id: string): $CancellablePromise<$models.Item> {
    return $Call.ByID(865420334, id).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * ListItems 按过滤条件查询条目（TagPath 含子孙标签）。
 */
export function ListItems(query: $models.ListQuery): $CancellablePromise<$models.Item[]> {
    return $Call.ByID(1509769421, query).then(($result: any) => {
        return $$createType2($result);
    });
}

/**
 * OpenItem 用系统默认应用打开源文件。
 */
export function OpenItem(id: string): $CancellablePromise<void> {
    return $Call.ByID(174901256, id);
}

/**
 * OpenItemLocation 在系统文件管理器中定位源文件。
 */
export function OpenItemLocation(id: string): $CancellablePromise<void> {
    return $Call.ByID(2520393503, id);
}

/**
 * PickFiles 打开系统文件选择器（多选）。
 */
export function PickFiles(): $CancellablePromise<string[]> {
    return $Call.ByID(3328361113).then(($result: any) => {
        return $$createType3($result);
    });
}

/**
 * PickFolder 打开系统目录选择器。
 */
export function PickFolder(): $CancellablePromise<string> {
    return $Call.ByID(1489609382);
}

/**
 * RemoveItems 删除条目（仅移除登记，不删除源文件）。
 */
export function RemoveItems(ids: string[]): $CancellablePromise<void> {
    return $Call.ByID(2657500993, ids);
}

/**
 * SetItemTags 用路径式标签名集合替换条目标签。
 */
export function SetItemTags(id: string, tagPaths: string[]): $CancellablePromise<void> {
    return $Call.ByID(1509354979, id, tagPaths);
}

/**
 * UpdateItemName 更新条目显示名。
 */
export function UpdateItemName(id: string, name: string): $CancellablePromise<void> {
    return $Call.ByID(426043794, id, name);
}

// Private type creation functions
const $$createType0 = $models.AddResult.createFrom;
const $$createType1 = $models.Item.createFrom;
const $$createType2 = $Create.Array($$createType1);
const $$createType3 = $Create.Array($Create.Any);
