// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * AddResult 是入库操作的结果摘要。
 */
export class AddResult {
    "added": number;
    "skipped": number;
    "failed": number;
    "items": Item[];

    /** Creates a new AddResult instance. */
    constructor($$source: Partial<AddResult> = {}) {
        if (!("added" in $$source)) {
            this["added"] = 0;
        }
        if (!("skipped" in $$source)) {
            this["skipped"] = 0;
        }
        if (!("failed" in $$source)) {
            this["failed"] = 0;
        }
        if (!("items" in $$source)) {
            this["items"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AddResult instance from a string or object.
     */
    static createFrom($$source: any = {}): AddResult {
        const $$createField3_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("items" in $$parsedSource) {
            $$parsedSource["items"] = $$createField3_0($$parsedSource["items"]);
        }
        return new AddResult($$parsedSource as Partial<AddResult>);
    }
}

/**
 * Candidate 是断链修复的候选位置。
 */
export class Candidate {
    "path": string;
    "score": number;
    "note": string;

    /** Creates a new Candidate instance. */
    constructor($$source: Partial<Candidate> = {}) {
        if (!("path" in $$source)) {
            this["path"] = "";
        }
        if (!("score" in $$source)) {
            this["score"] = 0;
        }
        if (!("note" in $$source)) {
            this["note"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Candidate instance from a string or object.
     */
    static createFrom($$source: any = {}): Candidate {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Candidate($$parsedSource as Partial<Candidate>);
    }
}

/**
 * Item 是库中的中心实体（可寻址资源）：file 或 url。
 */
export class Item {
    "id": string;

    /**
     * file | url
     */
    "kind": string;
    "name": string;
    "locator": string;
    "mime": string;
    "size": number;

    /**
     * unix 毫秒
     */
    "mtime": number;
    "width": number;
    "height": number;
    "durationMs": number;

    /**
     * ok | broken
     */
    "status": string;
    "tags": TagRef[];
    "createdAt": number;
    "updatedAt": number;

    /** Creates a new Item instance. */
    constructor($$source: Partial<Item> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("kind" in $$source)) {
            this["kind"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("locator" in $$source)) {
            this["locator"] = "";
        }
        if (!("mime" in $$source)) {
            this["mime"] = "";
        }
        if (!("size" in $$source)) {
            this["size"] = 0;
        }
        if (!("mtime" in $$source)) {
            this["mtime"] = 0;
        }
        if (!("width" in $$source)) {
            this["width"] = 0;
        }
        if (!("height" in $$source)) {
            this["height"] = 0;
        }
        if (!("durationMs" in $$source)) {
            this["durationMs"] = 0;
        }
        if (!("status" in $$source)) {
            this["status"] = "";
        }
        if (!("tags" in $$source)) {
            this["tags"] = [];
        }
        if (!("createdAt" in $$source)) {
            this["createdAt"] = 0;
        }
        if (!("updatedAt" in $$source)) {
            this["updatedAt"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Item instance from a string or object.
     */
    static createFrom($$source: any = {}): Item {
        const $$createField11_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("tags" in $$parsedSource) {
            $$parsedSource["tags"] = $$createField11_0($$parsedSource["tags"]);
        }
        return new Item($$parsedSource as Partial<Item>);
    }
}

/**
 * ListQuery 是条目列表的过滤条件。
 */
export class ListQuery {
    /**
     * 包含子孙
     */
    "tagPath"?: string;

    /**
     * 名称模糊匹配
     */
    "search"?: string;

    /**
     * file | url | ""
     */
    "kind"?: string;

    /**
     * ok | broken | ""
     */
    "status"?: string;
    "limit"?: number;
    "offset"?: number;

    /** Creates a new ListQuery instance. */
    constructor($$source: Partial<ListQuery> = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ListQuery instance from a string or object.
     */
    static createFrom($$source: any = {}): ListQuery {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ListQuery($$parsedSource as Partial<ListQuery>);
    }
}

/**
 * RepairItem 是修复中心的断链工作项。
 */
export class RepairItem {
    "id": string;
    "itemId": string;
    "itemName": string;
    "itemPath": string;

    /**
     * open | auto_fixed | manual_fixed | dismissed
     */
    "state": string;
    "candidates": string[];
    "createdAt": number;
    "updatedAt": number;

    /** Creates a new RepairItem instance. */
    constructor($$source: Partial<RepairItem> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("itemId" in $$source)) {
            this["itemId"] = "";
        }
        if (!("itemName" in $$source)) {
            this["itemName"] = "";
        }
        if (!("itemPath" in $$source)) {
            this["itemPath"] = "";
        }
        if (!("state" in $$source)) {
            this["state"] = "";
        }
        if (!("candidates" in $$source)) {
            this["candidates"] = [];
        }
        if (!("createdAt" in $$source)) {
            this["createdAt"] = 0;
        }
        if (!("updatedAt" in $$source)) {
            this["updatedAt"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RepairItem instance from a string or object.
     */
    static createFrom($$source: any = {}): RepairItem {
        const $$createField5_0 = $$createType4;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("candidates" in $$parsedSource) {
            $$parsedSource["candidates"] = $$createField5_0($$parsedSource["candidates"]);
        }
        return new RepairItem($$parsedSource as Partial<RepairItem>);
    }
}

/**
 * RescanResult 是全量扫描的结果摘要。
 */
export class RescanResult {
    "verified": number;
    "broken": number;
    "repaired": number;
    "newItems": number;

    /** Creates a new RescanResult instance. */
    constructor($$source: Partial<RescanResult> = {}) {
        if (!("verified" in $$source)) {
            this["verified"] = 0;
        }
        if (!("broken" in $$source)) {
            this["broken"] = 0;
        }
        if (!("repaired" in $$source)) {
            this["repaired"] = 0;
        }
        if (!("newItems" in $$source)) {
            this["newItems"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RescanResult instance from a string or object.
     */
    static createFrom($$source: any = {}): RescanResult {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new RescanResult($$parsedSource as Partial<RescanResult>);
    }
}

/**
 * Settings 是应用设置。
 */
export class Settings {
    "mcpEnabled": boolean;
    "mcpRunning": boolean;
    "mcpToken": string;

    /**
     * 本地服务（MCP+media）地址
     */
    "baseUrl": string;
    "mcpUrl": string;
    "mediaUrl": string;
    "libraryPath": string;
    "rescanOnStart": boolean;

    /** Creates a new Settings instance. */
    constructor($$source: Partial<Settings> = {}) {
        if (!("mcpEnabled" in $$source)) {
            this["mcpEnabled"] = false;
        }
        if (!("mcpRunning" in $$source)) {
            this["mcpRunning"] = false;
        }
        if (!("mcpToken" in $$source)) {
            this["mcpToken"] = "";
        }
        if (!("baseUrl" in $$source)) {
            this["baseUrl"] = "";
        }
        if (!("mcpUrl" in $$source)) {
            this["mcpUrl"] = "";
        }
        if (!("mediaUrl" in $$source)) {
            this["mediaUrl"] = "";
        }
        if (!("libraryPath" in $$source)) {
            this["libraryPath"] = "";
        }
        if (!("rescanOnStart" in $$source)) {
            this["rescanOnStart"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Settings instance from a string or object.
     */
    static createFrom($$source: any = {}): Settings {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Settings($$parsedSource as Partial<Settings>);
    }
}

/**
 * SettingsPatch 是设置更新补丁（指针字段表示"仅更新提供的项"）。
 */
export class SettingsPatch {
    "mcpEnabled"?: boolean | null;
    "rescanOnStart"?: boolean | null;

    /** Creates a new SettingsPatch instance. */
    constructor($$source: Partial<SettingsPatch> = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SettingsPatch instance from a string or object.
     */
    static createFrom($$source: any = {}): SettingsPatch {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SettingsPatch($$parsedSource as Partial<SettingsPatch>);
    }
}

/**
 * Stats 是库统计信息。
 */
export class Stats {
    "itemCount": number;
    "totalSize": number;
    "fileCount": number;
    "urlCount": number;
    "brokenCount": number;
    "tagCount": number;
    "watchRootCount": number;
    "repairOpenCount": number;

    /** Creates a new Stats instance. */
    constructor($$source: Partial<Stats> = {}) {
        if (!("itemCount" in $$source)) {
            this["itemCount"] = 0;
        }
        if (!("totalSize" in $$source)) {
            this["totalSize"] = 0;
        }
        if (!("fileCount" in $$source)) {
            this["fileCount"] = 0;
        }
        if (!("urlCount" in $$source)) {
            this["urlCount"] = 0;
        }
        if (!("brokenCount" in $$source)) {
            this["brokenCount"] = 0;
        }
        if (!("tagCount" in $$source)) {
            this["tagCount"] = 0;
        }
        if (!("watchRootCount" in $$source)) {
            this["watchRootCount"] = 0;
        }
        if (!("repairOpenCount" in $$source)) {
            this["repairOpenCount"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Stats instance from a string or object.
     */
    static createFrom($$source: any = {}): Stats {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Stats($$parsedSource as Partial<Stats>);
    }
}

/**
 * Tag 是路径式层级标签节点；Children 仅在构建树时填充。
 */
export class Tag {
    "id": string;

    /**
     * 路径最后一段
     */
    "name": string;

    /**
     * 完整路径（父/子/孙）
     */
    "path": string;
    "parentId": string;
    "itemCount": number;
    "children"?: (Tag | null)[];

    /** Creates a new Tag instance. */
    constructor($$source: Partial<Tag> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("path" in $$source)) {
            this["path"] = "";
        }
        if (!("parentId" in $$source)) {
            this["parentId"] = "";
        }
        if (!("itemCount" in $$source)) {
            this["itemCount"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Tag instance from a string or object.
     */
    static createFrom($$source: any = {}): Tag {
        const $$createField5_0 = $$createType7;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("children" in $$parsedSource) {
            $$parsedSource["children"] = $$createField5_0($$parsedSource["children"]);
        }
        return new Tag($$parsedSource as Partial<Tag>);
    }
}

/**
 * TagRef 是条目上标签的轻量引用。
 */
export class TagRef {
    "id": string;
    "path": string;

    /** Creates a new TagRef instance. */
    constructor($$source: Partial<TagRef> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("path" in $$source)) {
            this["path"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TagRef instance from a string or object.
     */
    static createFrom($$source: any = {}): TagRef {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new TagRef($$parsedSource as Partial<TagRef>);
    }
}

/**
 * WatchRoot 是用户登记的监听根目录。
 */
export class WatchRoot {
    "id": string;
    "path": string;
    "itemCount": number;

    /** Creates a new WatchRoot instance. */
    constructor($$source: Partial<WatchRoot> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("path" in $$source)) {
            this["path"] = "";
        }
        if (!("itemCount" in $$source)) {
            this["itemCount"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new WatchRoot instance from a string or object.
     */
    static createFrom($$source: any = {}): WatchRoot {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new WatchRoot($$parsedSource as Partial<WatchRoot>);
    }
}

// Private type creation functions
const $$createType0 = Item.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = TagRef.createFrom;
const $$createType3 = $Create.Array($$createType2);
const $$createType4 = $Create.Array($Create.Any);
const $$createType5 = Tag.createFrom;
const $$createType6 = $Create.Nullable($$createType5);
const $$createType7 = $Create.Array($$createType6);
