// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * SettingsService 提供应用设置（MCP 开关、启动扫描、令牌轮换）。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * GetSettings 返回当前设置（含 MCP/媒体服务地址）。
 */
export function GetSettings(): $CancellablePromise<$models.Settings> {
    return $Call.ByID(1992263654).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * RegenerateMcpToken 轮换 MCP 访问令牌。
 */
export function RegenerateMcpToken(): $CancellablePromise<string> {
    return $Call.ByID(3184395902);
}

/**
 * SetLibraryPath 记录库数据库位置（供 UI 展示）。
 */
export function SetLibraryPath(path: string): $CancellablePromise<void> {
    return $Call.ByID(3103953041, path);
}

/**
 * UpdateSettings 应用设置补丁。
 */
export function UpdateSettings(patch: $models.SettingsPatch): $CancellablePromise<void> {
    return $Call.ByID(2372991781, patch);
}

// Private type creation functions
const $$createType0 = $models.Settings.createFrom;
