// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * TagService 负责路径式层级标签的管理（Bear 模型：单父树、父选含子孙）。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * CreateTag 创建标签。name 可为单个标签名（配合 parentPath）或完整路径（如 a/b/c）。
 * 路径中间层不存在时自动创建。
 */
export function CreateTag(name: string, parentPath: string): $CancellablePromise<$models.Tag> {
    return $Call.ByID(663292310, name, parentPath).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * DeleteTag 删除标签及其整个子树（条目的其他标签保留）。
 */
export function DeleteTag(path: string): $CancellablePromise<void> {
    return $Call.ByID(2885835147, path);
}

/**
 * ListTags 返回完整标签树（每个节点带直接条目数与子节点）。
 */
export function ListTags(): $CancellablePromise<$models.Tag[]> {
    return $Call.ByID(1480178023).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * MoveTag 把标签（含子树）移动到 newParentPath 下。
 */
export function MoveTag(path: string, newParentPath: string): $CancellablePromise<void> {
    return $Call.ByID(3275072549, path, newParentPath);
}

/**
 * RenameTag 重命名标签最后一段，并批量更新所有子孙的路径前缀。
 */
export function RenameTag(path: string, newName: string): $CancellablePromise<void> {
    return $Call.ByID(581574900, path, newName);
}

// Private type creation functions
const $$createType0 = $models.Tag.createFrom;
const $$createType1 = $Create.Array($$createType0);
