// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * WatchService 后台监听监听根与条目父目录，近实时发现断链/移动/新文件。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * AddWatchRoot 登记监听根并立即索引（幂等）。
 */
export function AddWatchRoot(path: string): $CancellablePromise<$models.WatchRoot> {
    return $Call.ByID(2015409059, path).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * ListWatchRoots 返回监听根列表。
 */
export function ListWatchRoots(): $CancellablePromise<$models.WatchRoot[]> {
    return $Call.ByID(2105297925).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * RemoveWatchRoot 移除监听根（不删除条目）。
 */
export function RemoveWatchRoot(id: string): $CancellablePromise<void> {
    return $Call.ByID(2719520864, id);
}

/**
 * Start 初始化监听并启动事件循环。
 */
export function Start(): $CancellablePromise<void> {
    return $Call.ByID(2779936983);
}

/**
 * Stop 停止监听。
 */
export function Stop(): $CancellablePromise<void> {
    return $Call.ByID(4213007549);
}

// Private type creation functions
const $$createType0 = $models.WatchRoot.createFrom;
const $$createType1 = $Create.Array($$createType0);
