#!/usr/bin/env node

/**
 * 图标生成脚本
 *
 * 读取 packages/web-ui/icons.used.json, 从 @iconify-json/<set>/icons.json 提取图标数据,
 * 生成 packages/web-ui/src/icons/generated/<name>.ts 和 barrel index.ts。
 *
 * Usage: node --experimental-strip-types packages/web-ui/scripts/generate-icons.ts
 */

import { readFileSync, writeFileSync, mkdirSync } from 'node:fs'
import { resolve, dirname } from 'node:path'
import { fileURLToPath } from 'node:url'

const __dirname = dirname(fileURLToPath(import.meta.url))
const PKG_ROOT = resolve(__dirname, '..')
const ICONS_USED_PATH = resolve(PKG_ROOT, 'icons.used.json')
const OUT_DIR = resolve(PKG_ROOT, 'src/icons/generated')
const INDEX_PATH = resolve(PKG_ROOT, 'src/icons/index.ts')

/** 读取 icons.used.json，返回 [{ set, name }] */
function readUsedIcons(): Array<{ set: string; name: string }> {
  const raw = JSON.parse(readFileSync(ICONS_USED_PATH, 'utf8')) as string[]
  return raw.map(entry => {
    const [set, ...rest] = entry.split(':')
    return { set, name: rest.join(':') }
  })
}

/** 从 @iconify-json/<set>/icons.json 加载图标数据 */
function loadIconSet(set: string): Record<string, { body: string; width?: number; height?: number }> {
  const jsonPath = resolve(PKG_ROOT, `node_modules/@iconify-json/${set}/icons.json`)
  const data = JSON.parse(readFileSync(jsonPath, 'utf8')) as {
    icons: Record<string, { body: string; width?: number; height?: number }>
  }
  return data.icons
}

/** kebab-case 转 camelCase */
function toCamelCase(kebab: string): string {
  return kebab.replace(/-([a-z0-9])/g, (_, c) => c.toUpperCase())
}

/** 写入单个图标文件 */
function writeIconFile(iconName: string, data: { body: string; width?: number; height?: number }) {
  const w = data.width ?? 24
  const h = data.height ?? 24
  const content = `import type { IconifyIcon } from '@iconify/types'

export default {
  width: ${w},
  height: ${h},
  body: '${data.body.replace(/\\/g, '\\\\').replace(/'/g, "\\'")}'
} satisfies IconifyIcon
`
  const outPath = resolve(OUT_DIR, `${iconName}.ts`)
  writeFileSync(outPath, content, 'utf8')
  return iconName
}

/** 写入 barrel index.ts */
function writeIndex(entries: Array<{ name: string; camelName: string }>) {
  const lines = entries.map(e => `export { default as ${e.camelName} } from './generated/${e.name}'`)
  const content = `// Auto-generated by scripts/generate-icons.ts — do not edit manually.\n${lines.join('\n')}\n`
  writeFileSync(INDEX_PATH, content, 'utf8')
}

function main() {
  mkdirSync(OUT_DIR, { recursive: true })

  const used = readUsedIcons()

  // 按 set 分组加载
  const setCache = new Map<string, ReturnType<typeof loadIconSet>>()
  for (const { set } of used) {
    if (!setCache.has(set)) {
      setCache.set(set, loadIconSet(set))
    }
  }

  // 检查重名冲突（跨 set）
  const seen = new Map<string, string[]>()
  for (const { set, name } of used) {
    if (!seen.has(name)) seen.set(name, [])
    seen.get(name)!.push(set)
  }
  const collisions = new Set([...seen.entries()].filter(([, sets]) => sets.length > 1).map(([name]) => name))

  const barrel: Array<{ name: string; camelName: string }> = []

  for (const { set, name } of used) {
    const icons = setCache.get(set)!
    const data = icons[name]
    if (!data) {
      console.warn(`  ⚠️  icon "${set}:${name}" not found, skipping`)
      continue
    }

    const fileName = collisions.has(name) ? `${set}-${name}` : name
    writeIconFile(fileName, data)

    const camelName = toCamelCase(fileName)
    barrel.push({ name: fileName, camelName })
    console.log(`  ✅ ${set}:${name} → generated/${fileName}.ts`)
  }

  writeIndex(barrel)
  console.log(`\n📦 Barrel: src/icons/index.ts (${barrel.length} icons)`)
}

main()
