#!/usr/bin/env node

/**
 * 图标生成脚本
 *
 * 读取 icons.used.json, 从 @iconify-json/<set>/icons.json 提取图标数据,
 * 生成 src/icons/generated/<name>.ts 和 barrel index.ts。
 *
 * CLI:     node --experimental-strip-types scripts/generate-icons.ts
 * Vite:    import { generateIcons } from './scripts/generate-icons'
 */

import { readFileSync, writeFileSync, mkdirSync, existsSync } from 'node:fs'
import { resolve } from 'node:path'

/** kebab-case 转 camelCase */
function toCamelCase(kebab: string): string {
  return kebab.replace(/-([a-z0-9])/g, (_, c) => c.toUpperCase())
}

/** 内容无变化时跳过写入（Vite watcher 模式下避免死循环） */
function writeIfChanged(filePath: string, content: string) {
  if (existsSync(filePath) && readFileSync(filePath, 'utf8') === content) return
  writeFileSync(filePath, content, 'utf8')
}

/** 写入单个图标文件 */
function writeIconFile(outDir: string, iconName: string, data: { body: string }) {
  const content = `import type { IconifyIcon } from '@iconify/types'

export default {
  body: '${data.body.replace(/\\/g, '\\\\').replace(/'/g, "\\'")}'
} satisfies IconifyIcon
`
  writeIfChanged(resolve(outDir, `${iconName}.ts`), content)
}

/** 写入 barrel index.ts */
function writeIndex(indexPath: string, entries: Array<{ name: string; camelName: string }>) {
  const lines = entries.map(e => `export { default as ${e.camelName} } from './generated/${e.name}'`)
  const content = `// Auto-generated by scripts/generate-icons.ts — do not edit manually.\n${lines.join('\n')}\n`
  writeIfChanged(indexPath, content)
}

/**
 * 从 icons.used.json 生成图标模块
 *
 * @param pkgRoot web-ui 包根目录
 * @returns 生成的图标数量
 */
export async function generateIcons(pkgRoot: string) {
  const iconsUsedPath = resolve(pkgRoot, 'icons.used.json')
  const outDir = resolve(pkgRoot, 'src/icons/generated')
  const indexPath = resolve(pkgRoot, 'src/icons/index.ts')

  mkdirSync(outDir, { recursive: true })

  const raw = JSON.parse(readFileSync(iconsUsedPath, 'utf8')) as string[]
  const used = raw.map(entry => {
    const [set, ...rest] = entry.split(':')
    return { set, name: rest.join(':') }
  })

  // 按 set 分组加载
  const setCache = new Map<string, Record<string, { body: string; width?: number; height?: number }>>()
  for (const { set } of used) {
    if (!setCache.has(set)) {
      const mod = await import(`@iconify-json/${set}/icons.json`, { with: { type: 'json' } })
      setCache.set(set, mod.default.icons)
    }
  }

  const barrel: Array<{ name: string; camelName: string }> = []

  for (const { set, name } of used) {
    const icons = setCache.get(set)!
    const data = icons[name]
    if (!data) {
      console.warn(`  ⚠️  icon "${set}:${name}" not found, skipping`)
      continue
    }

    const fileName = `${set}-${name}`
    writeIconFile(outDir, fileName, data)

    const camelName = toCamelCase(fileName)
    barrel.push({ name: fileName, camelName })
  }

  writeIndex(indexPath, barrel)
  return barrel.length
}

/** CLI 自执行 */
const isCLI = import.meta.url === `file://${process.argv[1]}`
if (isCLI) {
  const count = await generateIcons(resolve(import.meta.dirname, '..'))
  console.log(`📦 Generated ${count} icons`)
}
