/* eslint-disable */
/* prettier-ignore */
// oxfmt-ignore
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

import type {
  RouteRecordInfo,
  ParamValue,
  ParamValueOneOrMore,
  ParamValueZeroOrMore,
  ParamValueZeroOrOne,
} from 'vue-router'
import type { _ExtractParamParserType } from 'vue-router/experimental'

declare module 'vue-router' {
  interface TypesConfig {
    _ParamParsers: {}
    RouteNamedMap: import('vue-router/auto-routes').RouteNamedMap
    _RouteFileInfoMap: import('vue-router/auto-routes')._RouteFileInfoMap
  }
}

declare module 'vue-router/auto-routes' {
  /**
   * Route name map generated by vue-router
   */
  export interface RouteNamedMap {
    '/[...all]/': RouteRecordInfo<
      '/[...all]/',
      '/:all(.*)',
      { all: ParamValue<true> },
      { all: ParamValue<false> },
      never
    >
    '/components/avatar': RouteRecordInfo<
      '/components/avatar',
      '/components/avatar',
      Record<never, never>,
      Record<never, never>,
      never
    >
    '/components/badge': RouteRecordInfo<
      '/components/badge',
      '/components/badge',
      Record<never, never>,
      Record<never, never>,
      never
    >
    '/components/button': RouteRecordInfo<
      '/components/button',
      '/components/button',
      Record<never, never>,
      Record<never, never>,
      never
    >
    '/components/checkbox': RouteRecordInfo<
      '/components/checkbox',
      '/components/checkbox',
      Record<never, never>,
      Record<never, never>,
      never
    >
    '/components/context-menu': RouteRecordInfo<
      '/components/context-menu',
      '/components/context-menu',
      Record<never, never>,
      Record<never, never>,
      never
    >
    '/components/dialog': RouteRecordInfo<
      '/components/dialog',
      '/components/dialog',
      Record<never, never>,
      Record<never, never>,
      never
    >
    '/components/drawer': RouteRecordInfo<
      '/components/drawer',
      '/components/drawer',
      Record<never, never>,
      Record<never, never>,
      never
    >
    '/components/dropdown': RouteRecordInfo<
      '/components/dropdown',
      '/components/dropdown',
      Record<never, never>,
      Record<never, never>,
      never
    >
    '/components/empty': RouteRecordInfo<
      '/components/empty',
      '/components/empty',
      Record<never, never>,
      Record<never, never>,
      never
    >
    '/components/icon': RouteRecordInfo<
      '/components/icon',
      '/components/icon',
      Record<never, never>,
      Record<never, never>,
      never
    >
    '/components/input': RouteRecordInfo<
      '/components/input',
      '/components/input',
      Record<never, never>,
      Record<never, never>,
      never
    >
    '/components/input-number': RouteRecordInfo<
      '/components/input-number',
      '/components/input-number',
      Record<never, never>,
      Record<never, never>,
      never
    >
    '/components/popover': RouteRecordInfo<
      '/components/popover',
      '/components/popover',
      Record<never, never>,
      Record<never, never>,
      never
    >
    '/components/radio': RouteRecordInfo<
      '/components/radio',
      '/components/radio',
      Record<never, never>,
      Record<never, never>,
      never
    >
    '/components/segmented': RouteRecordInfo<
      '/components/segmented',
      '/components/segmented',
      Record<never, never>,
      Record<never, never>,
      never
    >
    '/components/select': RouteRecordInfo<
      '/components/select',
      '/components/select',
      Record<never, never>,
      Record<never, never>,
      never
    >
    '/components/slider': RouteRecordInfo<
      '/components/slider',
      '/components/slider',
      Record<never, never>,
      Record<never, never>,
      never
    >
    '/components/spinner': RouteRecordInfo<
      '/components/spinner',
      '/components/spinner',
      Record<never, never>,
      Record<never, never>,
      never
    >
    '/components/svg-draw-lines': RouteRecordInfo<
      '/components/svg-draw-lines',
      '/components/svg-draw-lines',
      Record<never, never>,
      Record<never, never>,
      never
    >
    '/components/switch': RouteRecordInfo<
      '/components/switch',
      '/components/switch',
      Record<never, never>,
      Record<never, never>,
      never
    >
    '/components/textarea': RouteRecordInfo<
      '/components/textarea',
      '/components/textarea',
      Record<never, never>,
      Record<never, never>,
      never
    >
    '/components/theme': RouteRecordInfo<
      '/components/theme',
      '/components/theme',
      Record<never, never>,
      Record<never, never>,
      never
    >
    '/components/toast': RouteRecordInfo<
      '/components/toast',
      '/components/toast',
      Record<never, never>,
      Record<never, never>,
      never
    >
    '/components/tooltip': RouteRecordInfo<
      '/components/tooltip',
      '/components/tooltip',
      Record<never, never>,
      Record<never, never>,
      never
    >
    '/home/': RouteRecordInfo<'/home/', '/home', Record<never, never>, Record<never, never>, never>
  }

  /**
   * Route file to route info map by vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/[...all]/index.vue': {
      routes: '/[...all]/'
      views: never
      pathParamNames: never
    }
    'src/pages/components/avatar.vue': {
      routes: '/components/avatar'
      views: never
      pathParamNames: never
    }
    'src/pages/components/badge.vue': {
      routes: '/components/badge'
      views: never
      pathParamNames: never
    }
    'src/pages/components/button.vue': {
      routes: '/components/button'
      views: never
      pathParamNames: never
    }
    'src/pages/components/checkbox.vue': {
      routes: '/components/checkbox'
      views: never
      pathParamNames: never
    }
    'src/pages/components/context-menu.vue': {
      routes: '/components/context-menu'
      views: never
      pathParamNames: never
    }
    'src/pages/components/dialog.vue': {
      routes: '/components/dialog'
      views: never
      pathParamNames: never
    }
    'src/pages/components/drawer.vue': {
      routes: '/components/drawer'
      views: never
      pathParamNames: never
    }
    'src/pages/components/dropdown.vue': {
      routes: '/components/dropdown'
      views: never
      pathParamNames: never
    }
    'src/pages/components/empty.vue': {
      routes: '/components/empty'
      views: never
      pathParamNames: never
    }
    'src/pages/components/icon.vue': {
      routes: '/components/icon'
      views: never
      pathParamNames: never
    }
    'src/pages/components/input.vue': {
      routes: '/components/input'
      views: never
      pathParamNames: never
    }
    'src/pages/components/input-number.vue': {
      routes: '/components/input-number'
      views: never
      pathParamNames: never
    }
    'src/pages/components/popover.vue': {
      routes: '/components/popover'
      views: never
      pathParamNames: never
    }
    'src/pages/components/radio.vue': {
      routes: '/components/radio'
      views: never
      pathParamNames: never
    }
    'src/pages/components/segmented.vue': {
      routes: '/components/segmented'
      views: never
      pathParamNames: never
    }
    'src/pages/components/select.vue': {
      routes: '/components/select'
      views: never
      pathParamNames: never
    }
    'src/pages/components/slider.vue': {
      routes: '/components/slider'
      views: never
      pathParamNames: never
    }
    'src/pages/components/spinner.vue': {
      routes: '/components/spinner'
      views: never
      pathParamNames: never
    }
    'src/pages/components/svg-draw-lines.vue': {
      routes: '/components/svg-draw-lines'
      views: never
      pathParamNames: never
    }
    'src/pages/components/switch.vue': {
      routes: '/components/switch'
      views: never
      pathParamNames: never
    }
    'src/pages/components/textarea.vue': {
      routes: '/components/textarea'
      views: never
      pathParamNames: never
    }
    'src/pages/components/theme.vue': {
      routes: '/components/theme'
      views: never
      pathParamNames: never
    }
    'src/pages/components/toast.vue': {
      routes: '/components/toast'
      views: never
      pathParamNames: never
    }
    'src/pages/components/tooltip.vue': {
      routes: '/components/tooltip'
      views: never
      pathParamNames: never
    }
    'src/pages/home/index.vue': {
      routes: '/home/'
      views: never
      pathParamNames: never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info> ? Info['routes'] : keyof RouteNamedMap
}

export {}
