// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * 将操作系统能力限制在明确、可审查的桌面入口。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

/**
 * 始终交还给系统默认应用，Interweave 不接管外部内容。
 */
export function OpenExternal(target: string): $CancellablePromise<void> {
    return $Call.ByID(3347760165, target);
}

/**
 * 只定位外部文件，不修改文件系统内容。
 */
export function ShowInFileManager(filePath: string): $CancellablePromise<void> {
    return $Call.ByID(2523750525, filePath);
}
